choco upgrade filezilla -y
choco upgrade git -y
choco upgrade github-desktop -y
choco upgrade kitty -y
choco upgrade msys2 -y
choco upgrade notepadplusplus -y
choco upgrade oh-my-posh -y
choco upgrade vim -y
choco upgrade vscode -y
