choco upgrade chocolatey -y
choco upgrade bulkrenameutility -y
choco upgrade 7zip-zstd -y
choco upgrade agentransack -y
choco upgrade cutepdf -y
choco upgrade dvddecrypter -y
choco upgrade firefox -y
choco upgrade ghostscript -y
choco upgrade googlechrome -y
choco upgrade gimp -y
choco upgrade imgburn -y
choco upgrade inkscape -y
choco upgrade irfanview -y
choco upgrade microsoft-edge -y
choco upgrade microsoft-windows-terminal -y
choco upgrade nextdns -y
choco upgrade onedrive --ignore-checksums -y
choco upgrade powershell-core -y
choco upgrade paint.net -y
choco upgrade scribus -y
choco upgrade sumatrapdf -y
choco upgrade vlc -y
choco install zoom -y
