choco upgrade github-desktop -y
choco upgrade nvm -y
choco upgrade nvm.install -y
choco upgrade strawberryperl -y
choco pin remove -n=python
choco uninstall python -y
choco upgrade python -y
choco upgrade xmlstarlet -y
choco upgrade vscode -y
choco upgrade vscode.install -y
